import Head from "next/head";
import { AppProps } from "next/app";
import Header from "@/components/header";
import "@/assets/styles/globals.css";

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Component {...pageProps} />
    </>
  );
}
