FROM golang:latest


WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o httpserver ./cmd/httpserver


EXPOSE 8080

CMD ["./httpserver"]