name: Deploy API to GCP Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  deploy:
    name: Build and Deploy API
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write # Required for GCP authentication
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: pdf-edition-v2
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Configure Docker for GCP Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      
      - name: Build and Push Docker image
        working-directory: ./api
        run: make docker-push
      
      - name: Deploy to Cloud Run
        working-directory: ./api
        run: make deploy